//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class LuffarJobbDBEntities : DbContext
{
    public LuffarJobbDBEntities()
        : base("name=LuffarJobbDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Bids> Bids { get; set; }
    public DbSet<Employers> Employers { get; set; }
    public DbSet<JobComments> JobComments { get; set; }
    public DbSet<Jobs> Jobs { get; set; }
    public DbSet<Workers> Workers { get; set; }
}
